export const CLIENT_REQUIREMENTS_ITEMS = [
  "חשבון Cloudflare בבעלות הלקוח.",
  "גישה טכנית / אדמיניסטרטיבית למפתח.",
  "חשבון GROW בבעלות הלקוח.",
  "GROW userId.",
  "GROW pageCode.",
  "פרטי Sandbox ו-endpoint מאומתים.",
  "פרטי Production ו-endpoint מאומתים.",
  "פרטי API של GROW אם נדרשים בחשבון המאומת.",
  "אישור שהעברה בנקאית פעילה ב-GROW.",
  "אישור ש-API access פעיל ב-GROW.",
  "אישור ש-webhooks פעילים ב-GROW.",
  "אישור האם עמוד התשלום יכול להיות bank-transfer-only.",
  "אישור האם bank-transfer-only נתמך ברמת API/עמוד התשלום.",
  "payloads מאומתים של webhook מ-sandbox.",
  "payloads מאומתים של webhook מ-production אם הם שונים.",
  "אישור האם GROW מפיקה קבלות עבור תשלומי העברה בנקאית.",
  "החלטה האם מסמכים יופקו מ-GROW או מספק חיצוני.",
  "פרטי CRM / API אם מתחברים ל-CRM קיים.",
  "פרטי ספק חשבוניות / קבלות אם ההפקה מתבצעת מחוץ ל-GROW.",
  "החלטה על דומיין / סאב-דומיין, למשל payments.nimrodi.co.il או URL זמני של Cloudflare."
] as const;
